[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[build]
publish = "."
command = "echo 'No build command specified'"

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/.netlify/identity/*"

  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
for = "/assets/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/fonts/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"

  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/groups.html"
to = "/Groups.html"
status = 301

[[redirects]]
from = "/"
to = "/home.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]
